name: "Minor Release"
on:
  workflow_dispatch:

jobs:
  release-minor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout prerelease/minor
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 # Needed to do a proper push
          ref: prerelease/minor # This job only works on prerelease/minor

      - name: Push to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: refs/heads/main

      ## This step installs node and sets up several matchers (regex matching for Github
      ## Annotations). See
      ## https://github.com/actions/setup-node/blob/25316bbc1f10ac9d8798711f44914b1cf3c4e954/src/main.ts#L58-L65
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      ## The caching steps create a cache key based on the OS and hash of the yarn.lock file. A
      ## cache hit will copy files from Github cache into the `node_modules` and `.cache/cypress`
      ## folders. A cache hit will skip the cache steps
      - name: Cache node modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-hash-${{ hashFiles('yarn.lock') }}

      - name: Install github action package
        run: yarn add @actions/github

      - name: Cancel release action
        run: node utils/cancel-work.js
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Success Message
        run: echo "Release successful. Check out https://github.com/Workday/canvas-kit/actions/workflows/release.yml to see the release job start."

      - name: Failure Message
        if: failure()
        run: echo "Make sure there are no changes https://github.com/Workday/canvas-kit/compare/prerelease/minor...master and try again."
